# Python Exercise Collection 2
This notebook contains exercises on the numpy material we covered during week 3. There are ~25 problems here of increasing difficulty. The hardest exercises are beyond the difficulty level of what we'd put on a quiz, but may be close to what you might need to do for a lab report figure. For some of these questions there are multiple ways to get the answer, so don't feel like the provided solutions are the only way to do it.
</br></br>
Unless asked to, **do not** create any arrays by writing <code>np.array([])</code> and filling in the list with numbers.

### Exercise 1
Import the <code>numpy</code> package under its correct alias

In [2]:
# The below set of code insures that everyone should have the same random numbers
# for the problems in this notebook. You can ignore it and just write after the "Your code here" comment
np.random.seed(42)

# Your code here
import numpy as np

### Exercise 2
Create an array filled with zeros of size 10. Do not just fill <code>np.array()</code> with a list of zeros.

In [3]:
# Your code here
zero_arr = np.zeros(shape=10)
print(zero_arr, zero_arr.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)


### Exercise 3
Make the last element of the array from the previous problem equal to 1

In [4]:
# Your code here
zero_arr[-1] = 1
print(zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


### Exercise 4
Create and display a 1-dimensional numpy array containing the integers ranging from 10 to 49

In [5]:
# Your code here
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Exercise 5
Using the same array from the previous problem, reshape it to have 10 rows and four columns.

In [6]:
# Your code here
reshaped_arr = arr.reshape(10, 4)
print(reshaped_arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]]


### Exercise 6
Using the same array from the previous problem, create and display a new array which contains only the values in the last two rows and last two columns. Your answer should look like this $\begin{bmatrix}44 & 45 \\ 48 & 49 \end{bmatrix}$ except it'll appear as a list of lists rather than as a matrix.

In [7]:
# Your code here
last_two = reshaped_arr[-2:, -2:]
print(last_two)

[[44 45]
 [48 49]]


### Exercise 7
With the array you obtained in the previous problem, replace all even values with 0 and odd values with 1 only using numpy operations, no for loops.

In [8]:
# Your code here
even_odd = last_two % 2
print(even_odd)

[[0 1]
 [0 1]]


### Exercise 8
Using the array you made on exercise 5, create and display a new array containing only the elements which are divisible by 5.

In [9]:
# Your code here
divisible_by_five = reshaped_arr[reshaped_arr % 5 == 0]
print(divisible_by_five)

[10 15 20 25 30 35 40 45]


### Exercise 9
Use numpy to generate an array of size (10, 10) with random numbers between 0 and 1.

In [10]:
# Your code here
random_array = np.random.rand(10, 10)
print(random_array)
print(random_array.shape)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998 0.78517596
  0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
  0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802 0.54671028 0.18485446]
 [0.96958463 0.77513282 0.93949894 0.89482735 0.59789998 0.92187424
  0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
  0.14092422 0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212 0.81546143 0.70685734 0.72900717
  0.77127035 0.07404465 0.35846573 0.11586906]
 [0.86310343 0.62329813 0.33089802 0.06355835 0.31098232 0.32518332
  0.72960618

### Exercise 10
Find the max, min,  mean, standard deviation, and median of the array you made on the previous problem.

In [11]:
# Your code here
print(random_array.max())
print(random_array.min())
print(random_array.mean())
print(random_array.std())
print(np.median(random_array)) # Unfortunately the syntax for median is slightly different

0.9868869366005173
0.005522117123602399
0.47018074337820936
0.29599822663249037
0.4641424546894926


### Exercise 11
Use numpy to find the row and column position of the maximum element in your random array. Double check your work by indexing the array with your answer.

In [12]:
# Your code here
max_position = np.unravel_index(np.argmax(random_array), shape=random_array.shape)
print(max_position)
print(random_array.max() == random_array[max_position])

(6, 9)
True


### Exercise 12
Create an array of with 5 rows and 5 columns containing the values from 1 to 25. Then use indexing to create a new array containing the (3, 3) array occupying its center. Your answer should look like $\begin{bmatrix}7 & 8 & 9 \\ 12 & 13 & 24 \\ 17 & 18 & 19 \end{bmatrix}$

In [14]:
# Your code here
five_by_five_arr = np.arange(1, 26).reshape(5, 5)
inner_arr = five_by_five_arr[1:-1, 1:-1]
print(inner_arr)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


## Note: everything below this section was not covered in class, but is in the review notebook. I recommend you look at that before continuing, but some of you may be able to figure it out on your own.

### Exercise 13
Create a (6, 4) array with values ranging from 1 to 24. Then, without using for loops, find the values **and** positions of array elements for which both 4 and 6 are perfect factors? Double check your work by using your positions to index the array.

In [29]:
four_by_four = np.arange(1, 25).reshape(6, 4)
perfect_factors = four_by_four[(four_by_four % 4 == 0) & (four_by_four % 6 == 0)]
perfect_factor_positions = np.where((four_by_four % 4 == 0) & (four_by_four % 6 == 0))

print(four_by_four)
print(perfect_factors)
print(perfect_factor_positions)
print(perfect_factors == four_by_four[perfect_factor_positions])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[12 24]
(array([2, 5]), array([3, 3]))
[ True  True]


In [31]:
four_by_four = np.arange(1, 25).reshape(6, 2, 2)
perfect_factor_positions = np.where((four_by_four % 4 == 0) & (four_by_four % 6 == 0))

In [34]:
np.argwhere((four_by_four % 4 == 0) & (four_by_four % 6 == 0))

array([[2, 1, 1],
       [5, 1, 1]])