# Python Exercise Collection 2
This notebook contains exercises on the numpy material we covered during week 3. There are ~25 problems here of increasing difficulty. The hardest exercises are beyond the difficulty level of what we'd put on a quiz, but may be close to what you might need to do for a lab report figure. For some of these questions there are multiple ways to get the answer, so don't feel like the provided solutions are the only way to do it.
</br></br>
Unless asked to, **do not** create any arrays by writing <code>np.array([])</code> and filling in the list with numbers.

### Exercise 1
Import the <code>numpy</code> package under its correct alias

In [1]:
# Your code here
import numpy as np

### Exercise 2
Create an array filled with zeros of size 10. Do not just fill <code>np.array()</code> with a list of zeros.

In [13]:
# Your code here

### Exercise 3
Make the last element of the array from the previous problem equal to 1

In [15]:
# Your code here

### Exercise 4
Create and display a 1-dimensional numpy array containing the integers ranging from 10 to 49

In [14]:
# Your code here
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Exercise 5
Using the same array from the previous problem, reshape it to have 10 rows and four columns.

In [12]:
# Your code here
reshaped_arr = arr.reshape(10, 4)
print(reshaped_arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]]


### Exercise 6
Using the same array from the previous problem, create and display a new array which contains only the values in the last two rows and last two columns. Your answer should look like this $\begin{bmatrix}44 & 45 \\ 48 & 49 \end{bmatrix}$ except it'll appear as a list of lists rather than as a matrix.

In [18]:
# Your code here
last_two = reshaped_arr[-2:, -2:]
print(last_two)

[[44 45]
 [48 49]]


### Exercise 7
With the array you obtained in the previous problem, replace all even values with 0 and odd values with 1 only using numpy operations, no for loops.

In [21]:
# Your code here
print(last_two % 2)

[[0 1]
 [0 1]]


### Exercise 8
Using the array you made on exercise 5, create and display a new array containing only the elements which are divisible by 5.

In [24]:
# Your code here
divisible_by_five = reshaped_arr[reshaped_arr % 5 == 0]
print(divisible_by_five)

[10 15 20 25 30 35 40 45]


### Exercise 9
Use numpy to generate an array of size (10, 10) with random numbers between 0 and 1.

In [36]:
# Your code here
random_array = np.random.rand(10, 10)
print(random_array)
print(random_array.shape)

[[0.19026009 0.77614228 0.19830132 0.39504923 0.69115582 0.17721056
  0.52616058 0.98188299 0.91310492 0.66552388]
 [0.15336767 0.21653326 0.20114995 0.0897107  0.20164859 0.50133662
  0.14977969 0.35695412 0.04533911 0.42378659]
 [0.49611746 0.37132588 0.40273579 0.36219015 0.67032595 0.89198693
  0.35754603 0.82881309 0.39634565 0.84963105]
 [0.69511722 0.05608042 0.96758132 0.42309773 0.27041114 0.72606871
  0.78492033 0.30975095 0.89047376 0.52957852]
 [0.77485298 0.71195119 0.74057652 0.38403396 0.77767789 0.9621251
  0.36671815 0.28124129 0.46854106 0.53000044]
 [0.26544662 0.08318564 0.75049342 0.75847548 0.17467294 0.1267696
  0.76073241 0.295271   0.00125828 0.67487885]
 [0.47656785 0.38775967 0.67852839 0.0832443  0.04292152 0.55754189
  0.65523058 0.27200725 0.72707069 0.67178213]
 [0.87678686 0.9947366  0.45335451 0.53319208 0.55877625 0.48120069
  0.10168456 0.20510706 0.60043838 0.50087472]
 [0.14018013 0.06580108 0.55901305 0.74348149 0.36637587 0.07513195
  0.370092   0

### Exercise 10
Find the max, min,  mean, standard deviation, and median of the array you made on the previous problem.

In [35]:
# Your code here
print(random_array.max())
print(random_array.min())
print(random_array.mean())
print(random_array.std())
print(np.median(random_array)) # Unfortunately the syntax for median is slightly different

0.9936536423215767
0.008332067603614157
0.5326748285130273
0.26878118197551615
0.5301774885244839


### Exercise 11
Use numpy to find the row and column position of the maximum element in your random array. Double check your work by indexing the array with your answer.

In [38]:
# Your code here
max_position = np.unravel_index(np.argmax(random_array), shape=random_array.shape)
print(max_position)
print(random_array.max() == random_array[max_position])

(7, 1)
True
